apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-tempo
  labels:
    grafana_datasource: "1"  # Grafana auto-discovers ConfigMaps with this label
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        uid: tempo
        editable: true
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            # Optional: Link traces to logs if you have Loki
            datasourceUid: 'loki'
            tags: ['job', 'instance', 'pod', 'namespace']
          tracesToMetrics:
            # Optional: Link traces to metrics if you have Prometheus
            datasourceUid: 'prometheus'
          serviceMap:
            datasourceUid: 'prometheus'
          nodeGraph:
            enabled: true
          search:
            hide: false
          lokiSearch:
            datasourceUid: 'loki'
